### ISSUE TITLE
Alphasense OPC-N3 object is not being initiated correctly

### ISSUE THREAD

**Issue by dhhagan** [quant-aq/py-smps#42]
If you do not specify the `bin_labels`, the bin labels are not auto-generated as they should. Code [here](https://github.com/quant-aq/py-smps/blob/master/smps/models.py#L583)

**Comment by swawa** [comment]
I think this is still not solved as the columns (also the bins) are named with large initials for both possible data collection cases: when the file is stored on the internal SD-card or when the file is generated via the alphasense software.

columns on SD-card are named:
Bin0,Bin1,Bin2,Bin3,Bin4,Bin5,Bin6,Bin7,Bin8,Bin9,Bin10,Bin11,Bin12,Bin13,Bin14,Bin15,Bin16,Bin17,Bin18,Bin19,Bin20,Bin21,Bin22,Bin23,MToFBin1(us/3),MToFBin3,MToFBin5,MToFBin7,SamplingPeriod(s),SFR(ml/s),Temp(C),RH(%),PM_1.000(ug/m^3),PM_2.500(ug/m^3),PM_10.000(ug/m^3),#RjtGlitch,#RjtLong,#RjtRatio,#RjtRange,#FanRevs,LaserStatus

and columns written by the software are named:
OADateTime,Bin00,Bin01,Bin02,Bin03,Bin04,Bin05,Bin06,Bin07,Bin08,Bin09,Bin10,Bin11,Bin12,Bin13,Bin14,Bin15,Bin16,Bin17,Bin18,Bin19,Bin20,Bin21,Bin22,Bin23.MeanToFBin1(us).MeanToFBin3(us).MeanToFBin5(us).MeanToFBin7(us).Count/s.SamplingPeriod(s).SFR(ml/s).Temperature(C).RelativeHumidity(%).#RejectGlitch.#RejectLongTOF.#RejectRatio.#RejectOutOfRange.FanRevCount.LaserStatus.PM1(ug/m3).PM2.5(ug/m3).PM10(ug/m3).RollMean_PM1.RollMean_PM2.5.RollMean_PM10

best Swawa
