### ISSUE TITLE
smps.plots.heatmap error

### ISSUE THREAD

**Issue by Ethan-Barber** [quant-aq/py-smps#52]
**Describe the bug**
UFuncTypeError when using smps.plots.heatmap example

**To Reproduce**
1. import "Boston" example
2. copy example code for Boston example to produce heatmap
3. Receive error shown below

**Expected behavior**
Produces error: 

```py
"Cannot cast ufunc 'greater_equal' input 0 from dtype('<m8[ns]') to dtype('<m8') with casting rule 'same_kind'"
heatmap plot will not display.
```

**Screenshots**
[heatmaperror.pdf](https://github.com/quant-aq/py-smps/files/9312086/heatmaperror.pdf)

**Desktop (please complete the following information):**
 - OS: [ macOS Monterey]
 - Browser [Chrom]
 - Version [104.0.5112.79]

**Additional context**

**Comment by dhhagan** [comment]
Hi @Ethan-Barber can you answer a couple more questions?

1. What chip does your mac use? Intel or M1/M2?
2. What version of the package are you using? You can get this either by checking `smps.__version__` or `pip list`

**Comment by Ethan-Barber** [comment]
Hi @dhhagan 

1. My processor is: 2.3 GHz Dual-Core Intel Core i5
2. I am using version "smps v2.0.0"

**Comment by dhhagan** [comment]
Interesting. I can't seem to replicate the issue on my machine. Can you run `pip list` and post the results? I'm most interested in the version of `matplotlib` you're using, as it seems like that may be causing an issue. I've also just released version `2.1.0a0` which updates the required dependencies to allow for usage on M1 and M2 macs. It may be worth installing that and giving it a shot.

**Comment by Ethan-Barber** [comment]
Here are the results: 
[pip_list_results.txt](https://github.com/quant-aq/py-smps/files/9485249/pip_list_results.txt)

I tried installing the 2.1.0a0 update but am receiving an error when doing so.

**Comment by Ethan-Barber** [comment]
Update @dhhagan 

You were correct. I updated my version of matplotlib to 3.5.3 and it works now. 

Thank you so much for your help. :)
